// src/pages/result.jsx
import { useMemo, useEffect } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useEstimate } from '@/hooks/use-estimate'
import { calculateInvestment } from '@/lib/calculate'
import { formatMoney, formatPercent } from '@/lib/format'
import { ResultTable } from '@/components/result-table'
import { ResultInfo } from '@/components/result-info'
import { Button } from '@/components/ui/button'
import { ArrowLeft } from 'lucide-react'

export function Result() {
  const { estimate, canSubmit } = useEstimate()
  const navigate = useNavigate()

  useEffect(() => {
    if (!canSubmit) navigate('/')
  }, [canSubmit, navigate])

  const result = useMemo(() => {
    if (!canSubmit) return null
    return calculateInvestment({
      initialAmount: estimate.initialAmount,
      investmentDurationInMonths: estimate.investmentDurationInMonths,
      contributionPerMonth: estimate.contributionPerMonth,
      profitabilityPerMonth: estimate.profitabilityPerMonth,
      incomeGrowth: estimate.incomeGrowth || 0,
    })
  }, [estimate, canSubmit])

  if (!result) return null

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" asChild>
          <Link to="/">
            <ArrowLeft className="h-4 w-4" />
            Voltar
          </Link>
        </Button>
        <h1 className="text-xl font-semibold">Resultado</h1>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <ResultInfo label="Valor investido" value={formatMoney(result.totalInvested)} />
        <ResultInfo label="Juros recebidos" value={formatMoney(result.totalProfit)} />
        <ResultInfo label="Valor final" value={formatMoney(result.finalAmount)} />
        <ResultInfo label="Rentabilidade no período" value={formatPercent(result.totalProfitPercentage)} />
        <ResultInfo label="Estimativa de recebimento mensal" value={formatMoney(result.estimatedMonthlyIncome)} />
      </div>

      <ResultTable rows={result.rows} />
    </div>
  )
}

// src/components/environments/Result/Result.vue
<template>
  <v-container>
    <v-row align-md="stretch">
      <v-col md="8" sm="12" order="2" order-md="1" order-sm="1">
        <v-card>
          <v-card-title>
            <molecules-back-title to="/" title="Resultado" />
          </v-card-title>
          <v-row>
            <v-col>
              <organisms-result-table :rows="rows" height="500px" />
            </v-col>
          </v-row>
        </v-card>
      </v-col>
      <v-col
        class="d-flex flex-wrap align-content-space-between order-1 order-sm-2 order-md-2"
      >
        <h3 class="mb-auto">Dados finais</h3>
        <molecules-result-info
          v-for="({ number, title }, key) in finalInfos"
          :key="key"
          :number="number"
          :title="title"
        />
      </v-col>
    </v-row>
    <v-card> </v-card>
  </v-container>
</template>

<script>
  import { mapGetters } from 'vuex'
  import {
    GETTER_ESTIMATE,
    GETTER_ESTIMATE_FORM_CAN_SEND,
  } from '@/store/estimate'
  import { moneyFormatFilter } from '@/filters/money-format'
  import { percentageFormatFilter } from '@/filters/percentage-format'
  import OrganismsResultTable from '@/components/organisms/ResultTable/ResultTable'
  import MoleculesBackTitle from '@/components/molecules/BackTitle/BackTitle'
  import MoleculesResultInfo from '@/components/molecules/ResultInfo/ResultInfo'
  export default {
    name: 'EnvironmentsResult',
    components: {
      MoleculesResultInfo,
      MoleculesBackTitle,
      OrganismsResultTable,
    },
    computed: {
      ...mapGetters({
        estimate: GETTER_ESTIMATE,
        canViewResult: GETTER_ESTIMATE_FORM_CAN_SEND,
      }),
      rows() {
        const { estimate } = this
        const rows = []
        const makeRow = (
          month,
          contributionAmount,
          profitabilityPerMonth,
          accumulated = 0
        ) => ({
          month,
          contributionAmount,
          profitabilityPerMonth,
          accumulated:
            accumulated * (1 + profitabilityPerMonth) + contributionAmount,
        })

        let accumulated = 0
        let { contributionPerMonth } = estimate
        for (
          let month = 1;
          month <= estimate.investmentDurationInMonths;
          month++
        ) {
          if (month > 1 && month % 12 === 1)
            contributionPerMonth += estimate.incomeGrowth
          let row = makeRow(
            month,
            month === 1 ? estimate.initialAmount : contributionPerMonth,
            estimate.profitabilityPerMonth / 100,
            accumulated
          )
          accumulated = row.accumulated
          rows.push(row)
        }

        return rows
      },
      totalInvestedAmount() {
        return this.rows.reduce((acc, row) => acc + row.contributionAmount, 0)
      },
      totalProfitabilityAmount() {
        return this.finalAmount - this.totalInvestedAmount
      },
      totalProfitabilityPercentage() {
        return this.totalProfitabilityAmount / this.totalInvestedAmount
      },
      estimateMonthlyRecievements() {
        return (this.finalAmount * this.estimate.profitabilityPerMonth) / 100
      },
      finalAmount() {
        return this.rows[this.rows.length - 1].accumulated
      },
      finalInfos() {
        const makeInfo = (title, number) => ({ title, number })
        return [
          makeInfo(
            'Valor investido',
            moneyFormatFilter(this.totalInvestedAmount)
          ),
          makeInfo(
            'Juros recebidos',
            moneyFormatFilter(this.totalProfitabilityAmount)
          ),
          makeInfo('Valor final', moneyFormatFilter(this.finalAmount)),
          makeInfo(
            'Rentabilidade no período',
            percentageFormatFilter(this.totalProfitabilityPercentage)
          ),
          makeInfo(
            'Estimativa de recebimento mensal',
            moneyFormatFilter(this.estimateMonthlyRecievements)
          ),
        ]
      },
    },
    mounted() {
      if (!this.canViewResult) this.$router.push('/')
    },
  }
</script>
