// src/components/organisms/EstimateForm/EstimateForm.vue
<template>
  <v-form @submit.prevent="submit">
    <v-col cols="12">
      <v-text-field
        label="Aporte inicial"
        @input="updateInitialAmount"
        :value="estimate.initialAmount"
        outlined
        v-money="masks.money"
      />
    </v-col>

    <v-col cols="12">
      <v-text-field
        label="Duração em mêses"
        @input="updateInvestmentDurationInMonths"
        :value="estimate.investmentDurationInMonths"
        outlined
        hint="Por quantos mêses deixará o dinheiro investido"
        v-mask="'####'"
        class="ma-0 pa-0"
      />
      <v-row justify="space-between">
        <v-col class="py-0">
          <v-chip
            @click.prevent="selectYearOption(option)"
            v-for="option in yearsOptions"
            :key="option"
            class="mr-1"
            :outlined="option * 12 !== estimate.investmentDurationInMonths"
            color="secondary"
          >
            {{ option }} anos
          </v-chip>
        </v-col>
      </v-row>
    </v-col>

    <v-col cols="12">
      <v-text-field
        label="Aporte mensal"
        @input="updateContributionPerMonth"
        :value="estimate.contributionPerMonth"
        outlined
        v-money="masks.money"
      />
    </v-col>

    <v-col cols="12">
      <v-text-field
        label="Rentabilidade mensal estimada"
        @input="updateProfitabilityPerMonth"
        :value="estimate.profitabilityPerMonth"
        outlined
        v-money="masks.percentage"
        suffix="%"
        :hint="profitabilityHint"
        persistent-hint
      />
    </v-col>

    <v-col class="d-flex justify-center">
      <v-switch
        label="OPÇÕES AVANÇADAS"
        @change="updateAdvancedOptionsEnabled"
        :input-value="estimate.advancedOptionsEnabled"
        inset
        color="success"
      />
    </v-col>

    <template v-if="estimate.advancedOptionsEnabled">
      <v-col cols="12">
        <v-text-field
          label="Crescimento anual dos aporte"
          @input="updateIncomeGrowth"
          :value="estimate.incomeGrowth"
          outlined
          v-money="masks.money"
        />
      </v-col>
    </template>

    <v-col cols="12">
      <v-btn color="primary" block :disabled="!formCanSend" type="submit">
        ENVIAR
      </v-btn>
    </v-col>
  </v-form>
</template>

<script>
  import { mapActions, mapGetters, mapState } from 'vuex'
  import {
    ACTION_UPDATE_ESTIMATE_ADVANCED_OPTIONS_ENABLED,
    ACTION_UPDATE_ESTIMATE_CONTRIBUTION_PER_MONTH,
    ACTION_UPDATE_ESTIMATE_INCOME_GROWTH,
    ACTION_UPDATE_ESTIMATE_INITIAL_AMOUNT,
    ACTION_UPDATE_ESTIMATE_INVESTMENT_DURATION_IN_MONTHS,
    ACTION_UPDATE_ESTIMATE_PROFITABILITY_PER_MONTH,
    GETTER_ESTIMATE,
    GETTER_ESTIMATE_FORM_CAN_SEND,
  } from '@/store/estimate'
  import { STORE_ESTIMATE_STATE, STORE_MASKS_STATE } from '@/store'

  export default {
    name: 'EstimateForm',
    data() {
      return {
        yearsOptions: [5, 10, 15, 20, 30],
        yearProfitability: [6, 7.5, 9, 12],
      }
    },
    computed: {
      ...mapState({
        estimate: STORE_ESTIMATE_STATE,
        masks: STORE_MASKS_STATE,
      }),
      ...mapGetters({
        formCanSend: GETTER_ESTIMATE_FORM_CAN_SEND,
        parsedEstimate: GETTER_ESTIMATE,
      }),
      profitabilityHint() {
        const yearProfitability = (
          this.parsedEstimate.profitabilityPerMonth * 12
        )
          .toFixed(2)
          .replace(/\./g, ',')
        return `${yearProfitability}% por ano`
      },
    },
    methods: {
      ...mapActions({
        updateInitialAmount: ACTION_UPDATE_ESTIMATE_INITIAL_AMOUNT,
        updateInvestmentDurationInMonths: ACTION_UPDATE_ESTIMATE_INVESTMENT_DURATION_IN_MONTHS,
        updateContributionPerMonth: ACTION_UPDATE_ESTIMATE_CONTRIBUTION_PER_MONTH,
        updateProfitabilityPerMonth: ACTION_UPDATE_ESTIMATE_PROFITABILITY_PER_MONTH,
        updateIncomeGrowth: ACTION_UPDATE_ESTIMATE_INCOME_GROWTH,
        updateAdvancedOptionsEnabled: ACTION_UPDATE_ESTIMATE_ADVANCED_OPTIONS_ENABLED,
      }),
      selectYearOption(option) {
        this.updateInvestmentDurationInMonths(option * 12)
      },
      submit() {
        this.$router.push({
          path: '/resultado',
        })
      },
    },
  }
</script>

// src/components/estimate-form.jsx
import { useNavigate } from 'react-router-dom'
import { useEstimate } from '@/hooks/use-estimate'
import { CurrencyInput, PercentageInput, MaskedNumberInput } from '@/components/currency-input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'

const YEAR_OPTIONS = [5, 10, 15, 20, 30]

export function EstimateForm() {
  const { estimate, update, canSubmit } = useEstimate()
  const navigate = useNavigate()

  const handleSubmit = (e) => {
    e.preventDefault()
    if (canSubmit) navigate('/resultado')
  }

  const annualProfitability = ((estimate.profitabilityPerMonth || 0) * 12).toFixed(2).replace('.', ',')

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <CurrencyInput
        label="Aporte inicial"
        value={estimate.initialAmount}
        onValueChange={(v) => update('initialAmount', v)}
      />

      <div className="space-y-2">
        <MaskedNumberInput
          label="Duração em meses"
          value={estimate.investmentDurationInMonths}
          onValueChange={(v) => update('investmentDurationInMonths', v)}
          hint="Por quantos meses deixará o dinheiro investido"
          isAllowed={(values) => !values.floatValue || values.floatValue <= 9999}
        />
        <div className="flex flex-wrap gap-1.5">
          {YEAR_OPTIONS.map((year) => (
            <Badge
              key={year}
              variant={year * 12 === estimate.investmentDurationInMonths ? 'default' : 'outline'}
              onClick={() => update('investmentDurationInMonths', year * 12)}
            >
              {year} anos
            </Badge>
          ))}
        </div>
      </div>

      <CurrencyInput
        label="Aporte mensal"
        value={estimate.contributionPerMonth}
        onValueChange={(v) => update('contributionPerMonth', v)}
      />

      <PercentageInput
        label="Rentabilidade mensal estimada"
        value={estimate.profitabilityPerMonth}
        onValueChange={(v) => update('profitabilityPerMonth', v)}
        hint={`${annualProfitability}% por ano`}
      />

      <div className="flex items-center gap-3 py-2">
        <Switch
          checked={estimate.advancedOptionsEnabled}
          onCheckedChange={(v) => update('advancedOptionsEnabled', v)}
        />
        <Label className="text-sm font-medium">Opções avançadas</Label>
      </div>

      {estimate.advancedOptionsEnabled && (
        <CurrencyInput
          label="Crescimento anual dos aportes"
          value={estimate.incomeGrowth}
          onValueChange={(v) => update('incomeGrowth', v ?? 0)}
        />
      )}

      <Button type="submit" disabled={!canSubmit} className="w-full">
        Calcular
      </Button>
    </form>
  )
}
